Надо подкачаться
htmlacademy-javascript/1750401-kekstagram-24 pull request #10
Opened 2021-11-08 19:24 UTC by Eric938

2021-11-08 20:38 UTC, AlexMasterov requested changes

2021-11-08 20:38 UTC, AlexMasterov commented on js/modules/api.js
> +    .catch((error) => showAlert(error));
https://github.com/htmlacademy-javascript/1750401-kekstagram-24/blob/47877f8ae9d5fc7d2632eb9878f98bb52ead63ad/js/modules/api.js#L1

Модуль с `api` не должен "знать" про DOM и тем более _неявно_ добавлять в него сообщения.

Вместо этого следует добавить коллбэке `onFail` и подобные функции вызывать в нем:

 
```diff
- .catch((error) => showAlert(error));
+ .catch(onFail);
```
```js
// main.js
const onDataLoadSuccess = (data) => { ... };
const onDataLoadFail = (error) => {
  showAlert(error); // <--
};

getData(onDataLoadSuccess, onDataLoadFail);
```

2021-11-08 20:38 UTC, AlexMasterov commented on js/modules/api.js
> +    });
```js
.catch(onFail);
```

2021-11-08 20:38 UTC, AlexMasterov commented on js/modules/api.js
> +
<details>
<summary>modules/api.js</summary>

https://github.com/htmlacademy-javascript/1750401-kekstagram-24/blob/47877f8ae9d5fc7d2632eb9878f98bb52ead63ad/js/modules/api.js#L4
https://github.com/htmlacademy-javascript/1750401-kekstagram-24/blob/47877f8ae9d5fc7d2632eb9878f98bb52ead63ad/js/modules/api.js#L21
https://github.com/htmlacademy-javascript/1750401-kekstagram-24/blob/47877f8ae9d5fc7d2632eb9878f98bb52ead63ad/js/modules/api.js#L23
</details>

`https://...`, `POST`

На защите проекта могут придраться.

Б7
> Названия констант (постоянных значений) написаны прописными (заглавными) буквами

2021-11-08 20:38 UTC, AlexMasterov commented on js/modules/edit-image.js
> +export {addEventOnScaleControlButtons, removeEventOnScaleControlButtons, cleanStyles, hideEffectLevel, cleanImageClasses, addImageEffect, removeEventEffect, addInitialInputValue};
```js
export {
  addEventOnScaleControlButtons,
  addImageEffect,
  addInitialInputValue,
  cleanImageClasses,
  cleanStyles,
  hideEffectLevel,
  removeEventEffect,
  removeEventOnScaleControlButtons,
};
```

2021-11-08 20:38 UTC, AlexMasterov commented on js/modules/submit-form.js
> +  imgUploadForm.addEventListener('submit', (evt) => {
Если _случайно_ вызывать функцию `setImgUploadSubmit` два раза, то на элементе `imgUploadForm` будет два обработчика для события `sumbit`.

2021-11-08 20:38 UTC, AlexMasterov commented on js/modules/submit-form.js
> +    );
```js
sendData(
  onSuccess,
  onFail,
  new FormData(evt.target),
);
```

2021-11-08 20:38 UTC, AlexMasterov commented on js/modules/utils.js
> +
<details>
<summary>modules/utils.js</summary>

https://github.com/htmlacademy-javascript/1750401-kekstagram-24/blob/47877f8ae9d5fc7d2632eb9878f98bb52ead63ad/js/modules/utils.js#L27-L35
</details>

**9x** alertContainer.`style`.`*`

> **9x** `alertContainer['style']['zIndex']`, `...`

```js
const style = alertContainer.style; // <--

style.zIndex = 100;
style.position = 'absolute';
style.left = 0;
style.top = 0;
style.right = 0;
style.padding = '50px 3px';
style.fontSize = '30px';
style.textAlign = 'center';
style.backgroundColor = 'red';
```

2021-11-08 20:38 UTC, AlexMasterov commented on js/modules/submit-form.js
> +
<details>
<summary>modules/submit-form.js</summary>

https://github.com/htmlacademy-javascript/1750401-kekstagram-24/blob/47877f8ae9d5fc7d2632eb9878f98bb52ead63ad/js/modules/submit-form.js#L17-L52
</details>

<details>
<summary>modules/submit-form.js</summary>

https://github.com/htmlacademy-javascript/1750401-kekstagram-24/blob/47877f8ae9d5fc7d2632eb9878f98bb52ead63ad/js/modules/submit-form.js#L54-L89
</details>

На защите  проекта _могут_ придраться.

Д14
> Отсутствует дублирование кода: повторяющиеся части кода переписаны как функции

2021-11-08 20:38 UTC, AlexMasterov commented on js/modules/submit-form.js
> +
<details>
<summary>Проблема</summary>

![image](https://user-images.githubusercontent.com/700213/140813461-b78060f2-4194-41dc-bab1-2fd924eb936a.png)

</details>

Если открыть форму добавления фото и выбрать любой фильтр (кроме оригинала), а затем попробовать отправить фото на сервер, то после показа сообщения об успешной/неуспешной отправки фото снова открыть форму добавления, можно увидеть, что выбран прежний фильтр, но сам эффект с фото снят.

В этом случае должен быть выбран оригинальный фильтр, как `checked`.

2021-11-08 20:38 UTC, AlexMasterov commented on js/modules/edit-image.js
>    effectsList.removeEventListener('change', onEffectListChange);
`effects`List + `change` !== on`Effect`ListChange

> effect`s`

Д4

2021-11-08 20:40 UTC, AlexMasterov commented on js/modules/api.js
> +    .then((photos) => {
```diff
- .then((photos) => {
+ .then((data) => {
```

2021-11-09 11:39 UTC, Eric938 commented on js/modules/submit-form.js
> +
Там, где ты говоришь, что на защите могут придраться, я исправлю, если придерутся, хорошо?

2021-11-09 11:53 UTC, merged