Правда или действие(часть 1)
htmlacademy-javascript/1750401-kekstagram-24 pull request #7
Opened 2021-11-02 14:49 UTC by Eric938

2021-11-02 23:16 UTC, AlexMasterov requested changes

2021-11-02 23:16 UTC, AlexMasterov commented on js/modules/new-image-loading.js
> +const hideImgUploadOverlay = () => imgUploadOverlay.classList.add('hidden');
<details>
<summary>modules/new-image-loading.js</summary>

https://github.com/htmlacademy-javascript/1750401-kekstagram-24/blob/83b25e609d3c387b171e669814cde8d805518156/js/modules/new-image-loading.js#L7
</details>
<details>
<summary>modules/gallery.js</summary>

https://github.com/htmlacademy-javascript/1750401-kekstagram-24/blob/83b25e609d3c387b171e669814cde8d805518156/js/modules/gallery.js#L55
</details>

Д14
> Отсутствует дублирование кода: повторяющиеся части кода переписаны как функции

Как вариант:
```js
// import { hideElement } from './dom-util.js'

hideElement(imgUploadOverlay);
hideElement(bigPicture);
```

2021-11-02 23:16 UTC, AlexMasterov commented on js/modules/new-image-loading.js
> +const cleanUploadFile = () => uploadFile.value = '';
<details>
<summary>modules/hashtags-validation.js</summary>

https://github.com/htmlacademy-javascript/1750401-kekstagram-24/blob/83b25e609d3c387b171e669814cde8d805518156/js/modules/hashtags-validation.js#L39
</details>

<details>
<summary>modules/new-image-loading.js</summary>

https://github.com/htmlacademy-javascript/1750401-kekstagram-24/blob/83b25e609d3c387b171e669814cde8d805518156/js/modules/new-image-loading.js#L9
</details>

Д14
> Отсутствует дублирование кода: повторяющиеся части кода переписаны как функции

Как вариант:
```js
// import { clearElement } from './dom-util.js'

clearElement(hashtagsText);
clearElement(uploadFile);
```

2021-11-02 23:16 UTC, AlexMasterov commented on js/modules/new-image-loading.js
> +  imgUploadOverlay.classList.remove('hidden');
<details>
<summary>modules/new-image-loading.js</summary>

https://github.com/htmlacademy-javascript/1750401-kekstagram-24/blob/83b25e609d3c387b171e669814cde8d805518156/js/modules/new-image-loading.js#L12
</details>
<details>
<summary>modules/gallery.js</summary>

https://github.com/htmlacademy-javascript/1750401-kekstagram-24/blob/83b25e609d3c387b171e669814cde8d805518156/js/modules/gallery.js#L23
</details>

Д14
> Отсутствует дублирование кода: повторяющиеся части кода переписаны как функции

2021-11-02 23:16 UTC, AlexMasterov commented on js/modules/comment-validation.js
> +commentText.addEventListener('input', () => {
Повторю, что валидация HTML5 отчасти создавалась для подобных простых случаев.

<details>
<summary>modules/comment-validation.js</summary>

https://github.com/htmlacademy-javascript/1750401-kekstagram-24/blob/83b25e609d3c387b171e669814cde8d805518156/js/modules/comment-validation.js#L7-L17
</details>

Можно сделать тоже самое с помощью добавления полю `commentText` (в разметку или через JS) _одного_ атрибута `maxLength="140"`.

2021-11-02 23:16 UTC, AlexMasterov commented on js/modules/hashtags-validation.js
> +hashtagsText.addEventListener('input', () => {
<details>
<summary>Проблема</summary>

![image](https://user-images.githubusercontent.com/700213/139964656-00d4883a-847c-4310-8d94-3bfbb2c7aab3.png)

</details>

См. ТЗ:
> хэш-теги нечувствительны к регистру: `#ХэшТег` и `#хэштег` считаются одним и тем же тегом

Нужно доработать валидацию.

2021-11-03 07:44 UTC, Eric938 commented on js/modules/hashtags-validation.js
> +  if (hashtagsText.value.length === 0) {hashtagsText.setCustomValidity('');}
Я добавил эту строку, потому что если ввести хэштег не правильно, передумать добавлять хэштеги вообще и просто стереть все, он не дает опубликовать фото, выдавая ошибку "неправильный формат хэштега". Я не придумал как это исправить по-другому, поэтому добавил эту строку. Убрать ее?

2021-11-03 10:50 UTC, AlexMasterov commented on js/modules/hashtags-validation.js
> +  if (hashtagsText.value.length === 0) {hashtagsText.setCustomValidity('');}
Ты прав.

```js
''.split(' ') // ['']
```

`Array.p.split` с пробелом `' '` в качестве разделителя на пустой строке возвращает массив с одной пустой строкой, что запускает цикл `for` с проверкой жадной регулярки, которая не находит `#` и один символ 😃

> Убрать ее?

Если бы функция `validateHashtags` использовалась где-то еще, то прямо в ней следовало обработать все случаи ТЗ, как этот с пустой строкой в массиве и отдельно доработать регулярку.

В нашем простом случае, если поле пусто, то можно сбросить сообщение о валидации и прерывать обработчик, недопустим на уровне выше такой ситуации:

```js
hashtagsText.addEventListener('input', () => {
  if (hashtagsText.value.length === 0) {
    hashtagsText.setCustomValidity('');
    return;
  }

  const hashtags = hashtagsText.value.split(separator);
  const validateMessage = validateHashtags(hashtags);

  hashtagsText.setCustomValidity(validateMessage);
});
```

2021-11-03 11:19 UTC, AlexMasterov approved these changes
👍🏻

Пожалуйста, мелкие замечания в остатке исправь при выполнении следующего задания. Не хочу с этим задерживать, уже нужно торопиться.

2021-11-03 11:19 UTC, AlexMasterov commented on js/modules/close-popup.js
> +  document.removeEventListener('keydown', here);
`here`

Д4
> Из названия обработчика события и функции-колбэка следует, что это обработчик

Варианты:
```diff
- const removeKeydownEventListener = (here) => {
+ const removeKeydownEventListener = (callback) => {
```
```diff
- const removeKeydownEventListener = (here) => {
+ const removeKeydownEventListener = (onKeydown) => {
```
> `handler` могут не пропустить

https://github.com/htmlacademy-javascript/1750401-kekstagram-24/blob/242fc2d6b05a5d2760658db5ee02c011dc8fbb3d/js/modules/gallery.js#L22-L24

Нужно также исправить для `addKeydownEventListener `.

> \+ функции выглядит утилитарно, можно перенести в `util`

2021-11-03 11:19 UTC, AlexMasterov commented on js/modules/hashtags-validation.js
> +  const validateMessages = {
```diff
- const validateMessages = {
+ const ValidateMessage = {
```
Б8
```js
// Перечисление
const StatusCode = {
  OK: 200,
  NOT_FOUND: 404,
  BAD_REQUEST: 400,
};
```

Также нужно `ValidateMessage` вынести из функции и разместить в начале модуля, как _константу_.

2021-11-03 11:19 UTC, merged